#!/bin/sh
sudo date +%Y%m%d -s 190730 && sudo date +%T -s 16:16
cat ~/code/42shells.github.io/tmp/2019-07-30-getting-started         > ~/code/42shells.github.io/_posts/2019-07-30-getting-started.md
git add -A && git commit -m "changes"

sudo date +%Y%m%d -s 190818 && sudo date +%T -s 20:44
cat ~/code/42shells.github.io/tmp/2019-08-18-4-months-4-workshops    > ~/code/42shells.github.io/_posts/2019-08-18-4-months-4-workshops.md
git add -A && git commit -m "changes"

sudo date +%Y%m%d -s 190923 && sudo date +%T -s 20:51
cat ~/code/42shells.github.io/tmp/2019-09-23-head-and-or-hand        > ~/code/42shells.github.io/_posts/2019-09-23-head-and-or-hand.md
git add -A && git commit -m "changes"

sudo date +%Y%m%d -s 191021 && sudo date +%T -s 16:19
cat ~/code/42shells.github.io/tmp/2019-10-21-jeweller-in-the-castle  > ~/code/42shells.github.io/_posts/2019-10-21-jeweller-in-the-castle.md
git add -A && git commit -m "changes"

sudo date +%Y%m%d -s 191028 && sudo date +%T -s 21:42
cat ~/code/42shells.github.io/tmp/2019-10-28-fritch-karl-fritch      > ~/code/42shells.github.io/_posts/2019-10-28-fritch-karl-fritch.md
git add -A && git commit -m "changes"

sudo date +%Y%m%d -s 191120 && sudo date +%T -s 21:45
cat ~/code/42shells.github.io/tmp/2019-11-20-the-munich-show         > ~/code/42shells.github.io/_posts/2019-11-20-the-munich-show.md
git add -A && git commit -m "changes"
